### ISSUE TITLE
Client ID Error

### ISSUE THREAD

**Issue by CasAdair** [WalshyDev/Discord-Spotify-RPC#33]
I followed the instructions for obtaining the client id but it says
`{ code: 4000, message: 'Invalid Client ID' }`

**Comment by CasAdair** [comment]
@WalshyDev

**Comment by WalshyDev** [comment]
Run a `git pull origin master` and try again, it should have been fixed. @PeashyScript

**Comment by CasAdair** [comment]
@WalshyDev I cloned the latest copy, and I'm still getting the same error

**Comment by CasAdair** [comment]
sorry for the late reply, my workload has increased as of late

**Comment by SerenModz21** [comment]
im getting that same error
